# workflow의 이름
name: CI

# 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
on:
  push:
    branches: [ "main" ] # main branch로 push 될 때 실행됩니다.
  pull_request:
    branches: [ "main" ] # main branch로 pull request될 때 실행됩니다.

# jobs 섹션
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    # 프로젝트 경로로 이동하지 않고 working-directory 설정
    - name: Build with Maven
      run: mvn clean package
      working-directory: ./shop/duckshop

    # 환경 변수 추가
    - name: Set environment variables for MySQL
      run: |
        echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
